config/routes.rb
Rails.application.routes.draw do
  resources :campsites
  resources :cities
  resources :regions
  resources :countries
  root 'home#index'
  get 'admin/adminpage'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Campsites page', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Admin Page
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <%= link_to "Country", countries_path, class: "dropdown-item" %>
            </li>
            <li>
              <%= link_to "Region", regions_path, class: "dropdown-item" %>
            </li>
            <li>
              <%= link_to "City", cities_path, class: "dropdown-item" %>
            </li>
            <li>
              <%= link_to "Campsites", campsites_path, class: "dropdown-item" %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<table class="table table-hover table-striped">
  <thead class=" table-info">
  <tr>
    <th>Campsite</th>
    <th>City</th>
    <th>Region</th>
    <th>Country</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody style="background-color: rgba(255,184,234,0.23)">
  <% Campsite.all.order(:city_id).each do |campsite| %>
    <tr class="align-middle">
      <td><%= campsite.campsite_name %></td>
      <td>
        <%
          city = City.find_by(id: campsite.city_id)
          if city
        %>
          <%= city.city_name %>
        <% else
             next
           end %>
      </td>
      <td>
        <%
          if city
            region = Region.find_by(id: city.region_id)
            if region
        %>
            <%= region.region_name %>
          <% else
               next
             end %>
          </td>
          <td>
            <% if region
                 country = Country.find_by(id: region.country_id)
                 if country %>
                <%= country.country_name %>
              <% else
                   next
                 end %>
            <% end %>
        <% end %>
        </td>
        <td colspan="3"></td>
        </tr>
  <% end %>
  </tbody>
</table>