config/routes.rb
Rails.application.routes.draw do
  resources :campsites
  resources :cities
  resources :regions
  resources :countries
  root 'home#index'
  get 'admin/adminpage'
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :regions
  validates_presence_of :country_name
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: %i[ show edit update destroy ]

  # GET /countries or /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1 or /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries or /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: "Country was successfully created." }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1 or /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: "Country was successfully updated." }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1 or /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: "Country was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def country_params
      params.require(:country).permit(:country_name)
    end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_form.html.erb
<%= form_with(model: country) do |form| %>
  <% if country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
        <% country.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="d-flex align-items-center align-middle">
    <div class="field form-group">
      <%= form.text_field :country_name, placeholder: 'New country name', class: "form-control" %>
    </div>
    <div class="col-1"></div>
    <div class="actions">
      <%= form.submit class: "btn btn-info"%>
    </div>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<% def edit_country(country) %>
  <%= render 'form', country: country %>
<% end %>

<table class="table table-striped table-hover">
  <thead class="table-info">
  <tr>
    <th>Country ID</th>
    <th>Country name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody style="background-color: rgba(255,184,234,0.23)">
  <% @countries.each do |country| %>
    <tr class="align-middle">
      <td><%= country.id %></td>
      <td><%= country.country_name %></td>
      <td><%= link_to '', edit_country(country) %></td>
      <td><%= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger"%></td>
    </tr>
  <% end %>
  </tbody>
</table>
<br/>


<button class="btn btn-dark" onclick="$('#newCountryForm').show()">
  Add a new country
</button>
<br/>
<br/>

<div id="newCountryForm" style="display: none">
  <% @country = Country.new %>
  <%= render 'form', country: @country %>
</div>

app/views/countries/new.html.erb
<h1>New Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Back', countries_path %>

app/views/countries/show.html.erb
<p class="card card-body">
  <strong>Country name:</strong>
  <%= @country.country_name %>
</p>

<%= link_to 'Edit', edit_country_path(@country), class: "btn btn-primary" %>
<%= link_to 'Back', countries_path, class: "btn btn-dark" %>