config/routes.rb
Rails.application.routes.draw do
  resources :campsites
  resources :cities
  resources :regions
  resources :countries
  root 'home#index'
  get 'admin/adminpage'
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :region
  has_many :campsites
  validates_presence_of :city_name, :region_id
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: %i[ show edit update destroy ]

  # GET /cities or /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1 or /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities or /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: "City was successfully created." }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1 or /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: "City was successfully updated." }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1 or /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: "City was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def city_params
      params.require(:city).permit(:city_name, :region_id)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.erb
<%= form_with(model: city) do |form| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <br>
      <div class="container-fluid py-5 card">
        <div class="bg-warning">
          <h2 class="display-7 fw-bold table-warning"><%= pluralize(city.errors.count, "error") %> prohibited this
            city from being saved:</h2>
        </div>
        <ul>
          <% city.errors.each do |error| %>
            <li class="col-md-8 fs-4"><%= error.full_message %>. For all region ids click on the button "Regions" under
              the form
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <br>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :city_name, placeholder: "New city name", class: "form-control" %><br>
  </div>
  <div class="field form-group">
    <%= form.text_field :region_id, id: :city_region_id, placeholder: "Region id", class: "form-control" %><br>
  </div>
  <div class="d-flex align-items-center align-middle">
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Regions
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        <% Region.all.each do |region| %>
          <li>
            <div class="dropdown-item">
              <%= region.region_name %> id:  <%= region.id %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="col-1"></div>
    <div class="actions">
      <%= form.submit class: "btn btn-info" %>
    </div>
  </div>

<% end %>

app/views/cities/edit.html.erb
<%= render 'form', city: @city %>

<br>
<%= link_to 'Back', cities_path, class:"btn btn-dark" %>

app/views/cities/index.html.erb
<% def edit_city(city) %>
  <%= render 'form', city: city %>
<% end %>

<table class="table table-hover table-striped">
  <thead class=" table-info">
  <tr>
    <th>City ID</th>
    <th>City</th>
    <th>Region</th>
    <th>Country</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody style="background-color: rgba(255,184,234,0.23)">
  <% @cities.each do |city| %>
    <tr class="align-middle">
      <td><%= city.id %></td>
      <td><%= city.city_name %></td>
      <td>
        <%
          region = Region.find_by(id: city.region_id)
          if region
        %>
          <%= region.region_name %>
        <% else %>
          Invalid region ID (<%= city.region_id %>)
        <% end %>
      </td>
      <td>
        <% if region
             country = Country.find_by(id: region.country_id)
             if country %>
            <%= country.country_name %>
          <% else %>
            Invalid country ID (<%= region.country_id %>)
          <% end %>
        <% end %>
      </td>
      <td><%= link_to '', edit_city(city) %></td>
      <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<button class="btn btn-dark" onclick="$('#newCityForm').show()">
  Add a new city
</button>
<br/>
<br/>

<div id="newCityForm" style="display: none">
  <% @city = City.new %>
  <%= render 'form', city: @city %>
</div>
<br><br>

app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p class="card card-body">
  <strong>City:</strong>
  <%= @city.city_name %>
  <strong>Region:</strong>
  <%
    region = Region.find_by(id: @city.region_id)
    if region
  %>
    <%= region.region_name %>
    <strong>Region ID:</strong>
    <%= region.id %>
    <strong>Country:</strong>
    <% country = Country.find_by(id: region.country_id)
       if country %>
      <%= country.country_name %>
      <strong>Country ID:</strong>
      <%= country.id %>
    <% else %>
      No such a country with id <%= region.country_id %>
    <% end %>
  <% else %>
    No such a region with id <%= city.region_id %>
  <% end %>
</p>


<%= link_to 'Edit', edit_city_path(@city), class: 'btn btn-primary'%>
<%= link_to 'Back', cities_path, class: "btn btn-dark" %>