config/routes.rb
Rails.application.routes.draw do
  resources :campsites
  resources :cities
  resources :regions
  resources :countries
  root 'home#index'
  get 'admin/adminpage'
end

app/models/region.rb
class Region < ApplicationRecord
  belongs_to :country
  has_many :cities
  validates_presence_of :region_name, :country_id
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: %i[ show edit update destroy ]

  # GET /regions or /regions.json
  def index
    @regions = Region.all
  end

  # GET /regions/1 or /regions/1.json
  def show
  end

  # GET /regions/new
  def new
    @region = Region.new
  end

  # GET /regions/1/edit
  def edit
  end

  # POST /regions or /regions.json
  def create
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        format.html { redirect_to @region, notice: "Region was successfully created." }
        format.json { render :show, status: :created, location: @region }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1 or /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to @region, notice: "Region was successfully updated." }
        format.json { render :show, status: :ok, location: @region }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1 or /regions/1.json
  def destroy
    @region.destroy
    respond_to do |format|
      format.html { redirect_to regions_url, notice: "Region was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def region_params
      params.require(:region).permit(:region_name, :country_id)
    end
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/regions/_form.html.erb
<%= form_with(model: region) do |form| %>
  <% if region.errors.any? %>
    <div id="error_explanation">
      <br>
      <div class="container-fluid py-5 card">
        <div class="bg-warning">
          <h2 class="display-7 fw-bold table-warning"><%= pluralize(region.errors.count, "error") %> prohibited this region from being
            saved:</h2>
        </div>
        <ul>
          <% region.errors.each do |error| %>
            <li class="col-md-8 fs-4"><%= error.full_message %>. For all regions ids click on the button "Regions" under the form
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <br>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :region_name, placeholder: "New region name", class: "form-control" %><br>
  </div>
  <div class="field form-group">
    <%= form.text_field :country_id, id: :region_country_id, placeholder: "Country id", class: "form-control" %><br>
  </div>
  <div class="d-flex align-items-center align-middle">
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Countries
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        <% Country.all.each do |country| %>
          <li>
            <div class="dropdown-item">
              <%= country.country_name %> id:  <%= country.id %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="col-1"></div>
    <div class="actions">
      <%= form.submit class: "btn btn-info" %>
    </div>
  </div>
<% end %>

app/views/regions/edit.html.erb
<%= render 'form', region: @region %>

<br>
<%= link_to 'Back', regions_path, class:"btn btn-dark" %>

app/views/regions/index.html.erb
<% def edit_region(region) %>
  <%= render 'form', region: region %>
<% end %>

<table class="table table-hover table-striped">
  <thead class=" table-info">
  <tr>
    <th>Region ID</th>
    <th>Region name</th>
    <th>Country name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody style="background-color: rgba(255,184,234,0.23)">
  <% @regions.each do |region| %>
    <tr class="align-middle">
      <td><%= region.id %></td>
      <td><%= region.region_name %></td>
      <td>
        <%
          country = Country.find_by(id: region.country_id)
          if country
        %>
          <%= country.country_name %>
        <% else %>
          Invalid country ID (<%= region.country_id %>)
        <% end %>

      </td>
      <td><%= link_to '', edit_region(region) %></td>
      <td><%= link_to 'Destroy', region, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"%></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<button class="btn btn-dark" onclick="$('#newRegionForm').show()">
  Add a new region
</button>
<br/>
<br/>

<div id="newRegionForm" style="display: none">
  <% @region = Region.new %>
  <%= render 'form', region: @region %>
</div>
<br><br>

app/views/regions/new.html.erb
<h1>New Region</h1>

<%= render 'form', region: @region %>

<%= link_to 'Back', regions_path %>

app/views/regions/show.html.erb
<p class="card card-body">
  <strong>Region name:</strong>
  <%= @region.region_name %>
  <strong>Country name:</strong>
  <%
    country = Country.find_by(id: @region.country_id)
    if country %>
    <%= country.country_name %>
    <strong>Country ID:</strong>
    <%= @region.country_id %>
  <% else %>
    No such a country with id <%= @region.country_id %>
  <% end %>


</p>

<%= link_to 'Edit', edit_region_path(@region), class: 'btn btn-primary'%>
<%= link_to 'Back', regions_path, class: "btn btn-dark" %>